### ISSUE TITLE
Exception on add

### ISSUE THREAD

**Issue by MisterY** [mikvor/money-conversion#11]
Hi, some users on Android are getting this exception:

>W/System.err(24261): java.lang.ArrayIndexOutOfBoundsException: length=16; index=16
W/System.err(24261): at info.javaperformance.money.MoneyLong.add(MoneyLong.java:142)
W/System.err(24261): at info.javaperformance.money.AbstractMoney.add(AbstractMoney.java:34)
W/System.err(24261): at info.javaperformance.money.AbstractMoney.subtract(AbstractMoney.java:55)

Any ideas what might be causing it? 
I can not get this on any of the test devices / emulators so just looking for some ideas.

Happens on:

************ DEVICE INFORMATION ***********
Brand: motorola
Device: peregrine
Model: XT1039
Id: LPB23.13-17
Product: peregrine_retde

************ FIRMWARE ************
SDK: 22
Release: 5.1
Incremental: 17

**Comment by MisterY** [comment]
Got some more details.
This happens with the following scenario:
total = -5.5999999523162842
x = 5
total = total.subtract(x);

In Money.add(MoneyLong other), m_precision == 16 while other.m_precision = 0.
This results in the search for MoneyFactory.MULTIPLIERS[16], which does not exist.

**Comment by MisterY** [comment]
As a workaround, now using 
    return MoneyFactory.fromDouble(d, Constants.DEFAULT_PRECISION);
instead 
    return MoneyFactory.fromString(value);

**Comment by MisterY** [comment]
So, I guess, a better option is to use

    Money result = MoneyFactory.fromString(value).truncate(Constants.DEFAULT_PRECISION);

**Comment by mikvor** [comment]
I have committed a fix for this case as well as 2 other paths on which it was possible to exceed max precision.
Though my unit test was slightly different. I had to call `MoneyFactory.fromString( "5.5999999523162842" )` instead to create a MoneyLong with precision=16.

**Comment by MisterY** [comment]
Excellent, thanks! Glad to see the project being supported. Could you let me know what is the license for the use of the library? I have just added it to our personal finance app: http://android.moneymanagerex.org/ and have given credits but am not sure under what kind of license are you providing the code.
I see that the similar (or perhaps the same) idea is used in the new JavaMoney libraries.

**Comment by mikvor** [comment]
Yeah, I try to support any open source code I have made public. It may take some time depending on my life, but should not take too long.

That's Apache 2.0. Should not create any issues for you.

It is good that someone is using this library in real apps. If you'll need some other functionality in this project - let me know.

**Comment by MisterY** [comment]
Thank you! I'll keep that in mind. Somewhere down the line a need or a situation will occur that will call for additions, probably, and it is good to know that the option is there to improve and add to the code base. Best wishes

**Comment by MisterY** [comment]
And thanks for the great implementation of the Money type!
