### ISSUE TITLE
Multiplication/division with Money type

### ISSUE THREAD

**Issue by MisterY** [mikvor/money-conversion#12]
Hi,

Quick question, or a feature request: Why is there no multiplication and/or division operations between the Money types?
I'm trying to calculate a simple currency conversion with the rates and am not sure what the best path would be. 
Currently the only available path is through long/double conversions. I'm wondering what the reasons are and if it is possible to stay within Money type throughout the operations.

**Comment by mikvor** [comment]
I don't exactly understand what you will get if you multiply dollars by dollars... Dollars^2?
In your case rates are just numbers, so you multiply or divide currency by a number. Am I wrong?

**Comment by MisterY** [comment]
Sorry, what I meant is that there is no Money.multiply(Money) method, only Money.multiply(long) and Money.multiply(double).
So, when trying to explicitely use Money type, to get the multiplication functioning, there have to be conversions involved to/from long or double types.
Hope that makes it a bit more clear.
