### ISSUE TITLE
Add compareTo method to both Money* classes

### ISSUE THREAD

**Issue by mikvor** [mikvor/money-conversion#7]
Comparing 2 Money instances is not possible via conversion to double (both long and BigDecimal have higher precision than double). It is not recommended to compare them via BigDecimal due to performance penalty.

We need to implement compareTo on both classes so that we can use it without unneeded conversions.

**Comment by Xtrinity** [comment]
I have a working compareTo() implementation and i'll issue a pull request for it later (i've placed my old version in my fork's `old-compare-to` branch). Preliminary tests on my machine show that the old version is a tad faster. Around x4 faster compared to that of `BigDecimal`'s `compareTo()` method if the precision is less than 4. Anything higher than that and it will actually be x5 times slower.

**Comment by mikvor** [comment]
I have just committed an implementation which covers most of normal use cases - comparing 2 MoneyLong values.
Comparing MoneyLong and MoneyBigDecimal requires more thought.
